package pruebaAnnotations;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;


//Podemos no darle un ID al bean, en este caso cogería el nombre de la clase con la primera letra en minúscula
@Component("ExperiencedSeller")
public class ExperiencedSeller implements Employees {

	@Autowired
	public ExperiencedSeller(CreateFinancialReport newFinancialReport) {
		this.newFinancialReport = newFinancialReport;
	}

	@Override
	public String getTasks() {
		// TODO Auto-generated method stub
		return "Sell, sell and sell";
	}

	@Override
	public String getReport() {
		// TODO Auto-generated method stub
		//return "Report generated by seller";
		return newFinancialReport.getFinalcialReport();
	}
	
	private CreateFinancialReport newFinancialReport;

}
